site_name: CoCoHub Docs 
nav:
  - About: index.md
  - Video Guides: 
    - CoCoHub: tutorials/videos.md
    - Developers: tutorials/developer_videos.md
    - Vendors: tutorials/authors_videos.md
  - Guides:
      - Incorporate a component to Dialogflow with fulfillment: tutorials/plug_coco_component_inside_dialogflow_conversation
      - Calling a CoCo from Dialogflow(externally): tutorials/use_a_component_with_dialogflow_external
  - Terminologies Overview:
#      - Agents, Goals, State, and Actions: concepts/goals.md
      - Conversational Component: concepts/convcomp.md
      - Context: concepts/context.md
  - Developers:
    - SDKs: SDKs.md
  - Vendors:
    - Vendor Toolkits: connectors.md
    - Publishing guidelines: vendor-guidelines.md
  - API Specs: api.md
  - ⬅️ Home: https://conversationalcomponents.com/
  - ⬅️ CoCoHub: https://marketplace.conversationalcomponents.com/

repo_url: 'https://github.com/conversationalcomponents/docs'

theme:
  name: material

markdown_extensions:
  - codehilite
  - admonition

extra:
  social:
    - type: 'github'
      link: 'https://github.com/conversationalcomponents'
    - type: 'facebook'
      link: 'https://facebook.com/ConversationalComponents'


google_analytics: ['UA-143011310-6', 'docs.conversationalcomponents.com']

extra_javascript:
  - js_extra/luckyo.js
